spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
#        format_sql: true
        generate_statistics: none
    open-in-view: false
logging:
  level:
    org.hibernate.stat: info
    org.springframework.security: DEBUG

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}

server:
  servlet:
    context-path: /api
admin:
  default:
    pass: ${ADMIN_PASS}


springdoc:
  api-docs:
    path: /api-docs